### ISSUE TITLE
Examine SRM Spread

### ISSUE THREAD

**Issue by LiSongMWO** [lisongmechlab/lsml#442]
I'm currently assuming that the SRM spread is following the same pattern as LB10X. However it has been pointed out that this may not be correct.

I would like help where some one has dropped into lobby and recorded the spread of a single SRM6 launcher from above (spectator mode) and the side and post these videos for me somewhere. Please contact me for more info.

**Comment by Question2** [comment]
I can answer this. Neema told me that SRMs actually curve outside by design before converging, and this is the image he used to explain it : https://static.mwomercs.com/img/neema/envelope.png

I tested it at 50m in the testing grounds and the spread is still tighter than at 100m.

**Comment by EmilyBjoerk** [comment]
When was this info obtained? Many things have changed recently. Also I need actual measurements in lobby to verify. Testing grounds is buggy and doesn't correctly calculate everything (for example laser burn time is not taken into account on cooldowns for example).

**Comment by Question2** [comment]
That info was obtained very recently,  around the start of december.

Havent heard of testing grounds not calculate everything. Did you report that bug to PGI at least?

**Comment by TheGreenHell** [comment]
I know that testing grounds DOES take beam time into account, because that's where I go to test my milisecond-perfect macros.  If beam time wasn't accounted for, then my macros would be off time and I'd have gaps in my firing pattern.  When I did my testing for the Locust-1V, I know it took the beam time into account because that mech has a 50% beam reduction, but my macros fired perfectly.

**Comment by EmilyBjoerk** [comment]
@TheGreenHell The burn time duration has since been fixed (this issue is 6 months old).

However the point still stands, it is not the same code that is running the live servers and on the testing grounds. Without thorough verification we must be careful using results from testing grounds as they have a history of being bugged.

**Comment by LiSongMWO** [comment]
Superseeded by #789 to look at all missile spreads.
