### ISSUE TITLE
2.0 Request: Ghost Heat Toggle Option

### ISSUE THREAD

**Issue by crazy6432** [lisongmechlab/lsml#501]
For UI 2.0, it would be nice to have a toggle option for ghost heat to know the time to overheat for firing weapons near-simultaneously (eg 9 medium lasers fired in a group of 4 and 5).

**Comment by sestrand** [comment]
I agree that this is something useful for the user. the UI definitely wants to assume alpha strike after alpha strike and not a more measured approach to firing all your guns at once...  most of us dont want to explode into space... what is the heat and damage over 5s without using all of your weapons to the point of ghost heat?  you cant really see that in LSML (or any other tool).

I dont know about adding a button for this, but I can work on the methods to do the heat math, if you want this worked on now.

**Comment by LiSongMWO** [comment]
Ghost heat is only included in the `alpha strike heat %` display, and this is technically correct. An alpha strike is everything at once. 

Sustained DPS, Max DPS, Burst damage etc assume you know what you're doing and do not trigger ghost heat.

If you want to see how much damage you can do in a short time window without triggering ghost heat (by staggering your shots by 0.5 seconds, i.e. not doing an alpha strike), change the burst duration to something like 0.5 seconds (it's a text field, you can type whatever you want into it):

![image](https://user-images.githubusercontent.com/5306929/187562256-b225524b-af34-4e82-abdf-47ccecb93b6b.png)

**Comment by LiSongMWO** [comment]
I believe that the underlying issue that this feature request aims to solve is already solved by the burst feature as above.

I realize it's not super obvious how to use it, and it's not clear that it's a text field where you can enter your desired duration.

My proposal is to add presets for 0.5 s, and 1.0 s in addition to the existing values. Update tooltips and wiki.

If you still think that a ghost heat button is necessary, please let me know. Otherwise I will consider this feature request satisified with the above changes.

**Comment by sestrand** [comment]
I do like your planned updates as well.

The way LSML works, it still assumes that you have fired all of your weapons together in burst.  which means it includes ghost heat.  there hsould be a way to get the equivalent burst but chain firing such that ghost heat weapons are not fired beyond the ghost heat weapon level.  (and some tooltip or indicator to show that is what is going on for this value)

**Comment by LiSongMWO** [comment]
I'm not sure I understand your comment. Ghost heat is only included into the alpha strike top two marked values in the screenshot? I believe that the burst damage shows what you're asking for, if I'm wrong, please explain how it's different from what you're asking for?

**Comment by sestrand** [comment]
It is certainly not clear in the UI if burst heat is or is not including ghost heat.  yes I see that there is no extra numbers beside the heat time... but the meaning of that was not intuitive to me.

I am looking in the code and loadout is used in the computation of heat over time... but the means to avoid ghost heat is not computed in the time to fire value.  you have to delay firing by .5 between groups that will ghost heat.  but that slows the firing rate and thus the eDPS for the burst time input.  LSML is assuming all can fire together over that time interval and just not computing ghost heat.  thus LSML is overestimating burst damage over that interval.  (if there is ghost heat).  not by a lot... 

so... perhaps some enhanced tool tip is needed to explain that the burst damage and heat assumes cyclical firing to avoid ghost heat.

and maybe some tweak to the calculation may be in order.  it may actually be impossible to avoid ghost heat without really stretching out the (burst) firing cycle for some builds.

**Comment by LiSongMWO** [comment]
General comment: I'm always concerned about UI layout and code complexity. Adding a button adds a "mode" to the UI it's an extra step, it adds more code and it takes up space in the UI. In general one can say "It's just one button it's not a big deal" but then that becomes a pattern and after a while it looks like the control board of a nuclear reactor, and if unlucky these toggles and features start having interactions and then it's not "just" a button anymore. 

I'd rather adjust the UI presentation in a way that the button isn't necessary. In this case by adjusting the burst display and default value and tooltips. 

Just to avoid any confusion. The burst damage display is "simulated" optimal trigger pulls ignoring that ghost heat is a thing. This is *not* just `dps*seconds`, you see this by adding a PPC and a short duration. If the PPC does 10 damage with 4 second firing period, then it does 2.5 DPS, and if you set the burst duration to any value between 0.1 and 4.9 you'll see 10 damage which is the weapon damage times how many firing periods you can fit in the burst time. 

The potential .5 second delay between groups of weapon to avoid ghost heat doesn't affect eDPS, it's just an offset and the DPS would be the same. However it can affect the burst damage and it's not currently taken into account because finding a "optimal" and straight forward way to compute how a pilot would group the weapons is probably impossible. For example: Say you have 6 LLAS, you can fire 4 without ghost heat. Do you fire them 4 + 2? No, you probably don't, you probably fire 3+3 for even distribution of damage between your groups. But the burst damage would be very different if set to less than 0.5 seconds as the "optimal" burst damage pattern is 4+2 so the burst would show something different than what you'd realistically do in game.

I think it's better to accept the fact that the burst damage display can technically overrestimate the burst amount by extending the burst time by 0.5 seconds to avoid ghost heat.

**Comment by sestrand** [comment]
I agree, no new button is required.

But, after using this tool for several years, I have just now come to understand what the burst value means.  So yes, please adjust the display and values and tooltips to make it more obvious.  that would be great.

**Comment by LiSongMWO** [comment]
I notice this from time to time that many users make assumptions about how some values are calculated and not notice that LSML actually goes out of it's way to compute those values in a much more accurate and complex way so that the stats shown reflect closer what you'd actually get in game, eFP vs rFP, burst, quirks, modifiers, map and engine heat taken into account etc.

It's a hard problem to solve, I feel like tooltips are insufficient and hard to discover, especially since you can't put so much text into a tooltip. I've put the big notice at the top of the download page for a very long time now to please take a look at: https://github.com/lisongmechlab/lsml/wiki/Statistics which explains all of this but that seems to also not be enough.

**Comment by LiSongMWO** [comment]
I have reworked the loadout info panel. I believe the new wording, tooltips and the (?) link to the explanation in https://github.com/lisongmechlab/lsml/wiki/Statistics#burst-damage--heat will help to alleviate confusion.

![image](https://user-images.githubusercontent.com/5306929/215300914-63da2b54-142a-4275-a0b0-2bf0362b59fc.png)

**Comment by LiSongMWO** [comment]
I have closed the issue now to reflect the effort comitted. If there are still parts that need clarification. Please open a new issue per issue.
