### ISSUE TITLE
Tooltip window disapears too quickly

### ISSUE THREAD

**Issue by Question2** [lisongmechlab/lsml#553]
When mousing over a component in the left hand window, the window frequently dissapears after a few short seconds, even if i do not move the mouse and my pointer is still over the component.

**Comment by EmilyBjoerk** [comment]
I presume you're talking about the tooltip on the equipment list on the left yes?

This is a known bug in Java 8 and will be fixed in Java 9 (not yet out)... unfortunately I haven't found a good workaround yet.  See here: https://bugs.openjdk.java.net/browse/JDK-8090477 .

Although annoying I don't know how I could fix it at the moment.
