### ISSUE TITLE
Add generic mech types

### ISSUE THREAD

**Issue by Wintersdark** [lisongmechlab/lsml#556]
Is it possible to add "generic" mechs?  Essentially, ones unbound by construction limits, so we can work on builds for upcoming mechs?  As an example, start with a 100t Clan Chassis, which can accept any engine, any equipment, any weapons.  Calculate values as normal, just allow any equipment/upgrades/engines/etc to be placed.  

I'd assume you'd just treat them like Battlemechs - you could go so far as to add, say, 6E/6B/6M to every component and allow up to 400 rated engines, add one of these for each tonnage, then call it a day, assuming having a separate window is substantially more work.

Derrick

**Comment by EmilyBjoerk** [comment]
This is actually a feasible idea for construction of unreleased 'Mechs. Adding 6E/6B/6M/ECM/6AMS or (Call it 6X maybe?) to all components (except legs), 10-400 engine limit. Just pick faction and tonnage. 

I'll give it a pondering and see if it is possible to do for 2.1 or 2.2 possibly.

**Comment by Wintersdark** [comment]
Wonderful, that would be fantastic!  That's exactly what I've been looking for, as it can be complex to theorycraft for unreleased chassis, particularly when you start thinking about FF, ES, fine engine and armor adjustments, etc.

**Comment by dario03** [comment]
Yeah this would be great. Any kind of custom mech builder would require the user to set limits at some point anyways, so having to limit ourselves while setting the equipment wouldn't be a big deal.

**Comment by dario03** [comment]
I was wondering, when you put the generic mechs in LSML would it be possible to have basically no limits? Stuff like
-IS, Clan, and Mixtech. Where the IS and Clan option would limit you to just one type and the mixtech would let you mix them.
-Weights outside of 20-100. If a limit is needed set it to something like 10-150 or 10-200.
-Engines bigger than 400. Don't know if those even existed in lore/tt but I think the weights are based on a formula with a couple of jumps in weight for larger gyros. (Not sure if that would work since its equipment and you get the data from the game files but you mentioned a rating of 10-400 and 10 isn't in the game.)
If any of those are something that doesn't take much while adding in the generic mechs I think that would be really cool. Being able to quickly see how something like a 150ton Omega with Clan xl475, clan large pulse lasers, clan er medium lasers, and IS ac5s would perform in MWO would be pretty awesome. But even just mechs over 100t or just mixtech would be cool.

**Comment by EmilyBjoerk** [comment]
I just realized that a lot of things depend on the weight of the 'Mech (just about everything to do with mobility and speed). So what I'll probably end up doing is creating a new "X" hard point that will allow anything and generating a "Generic" standard chassis for each faction and each tonnage (20-100) with "6X" hard points on each component besides the legs. I'll remove the engine limit so you can put anything that is in the data files (technically that is the same as setting 10-400 limit). So there'll be a bunch of "Generic 35t Clan" or similar 'Mechs.

**Comment by Wintersdark** [comment]
Sounds perfect!

**Comment by LiSongMWO** [comment]
Given the situation with development time for the past few years I don't think I'm ever going to get around to doing this so I'm closing this as won't fix.
