### ISSUE TITLE
Equipment Groups are not minimised on a single click.

### ISSUE THREAD

**Issue by silvercheckmate** [lisongmechlab/lsml#601]
In the Loadout / Mechlab screen, equipment groups are not minimised on single click, you have to double click or click exactly on the arrowhead. All other headers found throughout LSML minimise on a single click.

**Comment by LiSongMWO** [comment]
The equipment groups are part of a navigation tree structure, kind of like folders in windows. The garage folders also behave like this.

Changing this is more effort than it's worth as you need to create a whole cell factory and the expansion/collapse logic. I don't think I'll get around to doing this, especially since you just need to double click.
