### ISSUE TITLE
Alpha dmg calculation for RACs, Flamers, MGs

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#750]
**LSML version:** 2.0.11
**Screen resolution:** 3440x1440
**Java version:** 8u281

**Steps to reproduce issue:**
1. Open LSML
2. Click on any mech 

**Actual result:**
LSML reports alpha damage as a single shot for RACs and MGs,  and 1 second of dmg for flamer.

**Expected result:**
Something more like 1.5 second burst (with or without spin up) for all of the above to make them all consistent

discussion:
The longest duration laser is the heavy large with 1.45 seconds.  
If you made all of the above equal to that value... it would match what is required to hold the slowest laser on target for the alpha.

interestingly ... in that same laser duration window there are 5 weapons that can fire twice (ac2, lbx2 uac2, cac2 and cuac2).  

if you made the window equal to the fastest cooldown plus almost enough for the second shot (1.26s is 2xcuac2 cooldown) then you would need to shorten the time on target for the three laser weapons that have a duration longer than that.

anyway.  I offer that LSML could improve the alpha calc a bit to account for the face time required for teh RAC/MG and flamer to at least match that required for the heavy large laser.  and then also consider reducing that time and cutting short some lasers dmg also due to long face time exposure.

thanks for all of the work on this tool.

**Comment by LiSongMWO** [comment]
In order to scope this discussion properly: Alpha strike is the damage metric that is shown on your loadout's offensive summary. What you're describing is called burst damage, and LSML already shows it in the offensive summary. Alpha strike and burst damage have two very distinct meanings and I do not want to collate the two.

The goal of LSML is to make you play better, not necessarily just dump all the data or to even match what PGI shows. For this reason things have specific meanings and the metrics are intended to be used for decision making in specific scenarios and use cases:

* Burst damage: You know you're going to engage for sure, you're prepared. You've had time to spin up your guns and give yourself a pep-talk, call your mom tell her you love her and to check if you left the stove on... that kinda thing
* Sustained DPS: You're in a heat saturated fight, this is what you can do without shutting down.
* Max DPS: This is what you can do if you manage your heat externally (coolshots, standing in water, cooling off behind buildings etc)
* Alpha damage: This is your "oh-sheeet" damage, you don't know if you have a target until you need to shoot it. This is pop-tarting, hill humping, peek-a-boo, and "whooa! that dude came outta nowhere!"

In my opinion these metrics are working well for their intended purposes. RAC has poor alpha damage numbers, because it is poor for this type of engagement. You didn't have time to spin-up, you don't have a long face time. With lasers you can twitch shoot and track the beam for 1 second and still have a decent damage output, and most importantly. You know this is the case when you put heavy lasers on it, you have this is your mind when you study the characteristics of the loadout. Meanwhile with an RAC you haven't even gotten a single bullet out in that time. If anything, your argument is stronger for reducing lasers' alpha numbers to be shorter, rather than artificially increasing those of RACs.

If what you want to see is, how much can I do in a 2 second engagement, just set the burst tool to 2 seconds. Or in the weapons table just look at the DPS number instead because that's more true to what you are looking for.

**Comment by sestrand** [comment]
I don't disagree with your statements at all.  But LSML should at least be consistent.  I am not certain why 1 second of flamer is valid and not 1 second of MG.  I can accept that 1 sec spin up on the rac means zero alpha (or the single round).

I definitely think that an alpha of the large lasers should be reduced to be at least as short as the 1.26s.  

if you set all alpha to be what you can get done in 1 second, then there would be some more lasers that would have to be curtailed beyond the three I mentioned above.  I like your logic of popping and holding 1 second of laser/burst etc  which effectively eliminates racs (or providing 1 round) from ALPHA for that reason.  but to be consistent, with flamer, the MGs should also get 1 second not 1 round.

**Comment by LiSongMWO** [comment]
1.26 seconds is arbitrary and for anyone looking at the alpha value with a heavy laser equipped would be confused. There's a fine line here and I think it's fine as it is. At the very least it's not worth the effort and confusion that would ensue (there is ripe confusion already when the DPS numbers are different to other tools, see #746.

**Comment by sestrand** [comment]
1.26 is the shortest time it would take to have 2 shots form AC2/UAC2.  I
would call it much less arbitrary than the 1 sec allowed for the flamer in
the Alpha calculation currently set in LSMLw.  it would be confusing if you
dont have something on the screen defining what is an alpha. curerntly that
is the case, LSML apha already has teh same name but different meaning than
used in all others, but the result is different and lower without any
explanation.  other tools are using 5 sec for MG, Flamer and pre spunup
racs. and all of the laser duration, even though we know that is also hard
to hold in the way you are defining alpha.

my only real ask is that you convert MG to the same 1 sec you have on the
Flamer.

**Comment by sestrand** [comment]
and ideally add a mouse over popup telling everyone what is in your alpha.

**Comment by LiSongMWO** [comment]
I do not have 1 second set for anything on alpha. What you're seeing is a parse bug that caused flamers to have 10 times more DPS than they should. MG is correct at 0.1 damage per bullet.  Flamer doesn't have bullets, rate of fire or cooldown. I've normalised it to a rof of 10, matching MG. now showing the ridiculous alpha of 0.01 which to be fair is about what you can expect from a flamer anyway...
