### ISSUE TITLE
+ ##% max heat quirk not included in 

### ISSUE THREAD

**Issue by RosariusAU** [lisongmechlab/lsml#770]
Another patch, another bug!

**LSML version:** 2.0.14
**Screen resolution:** 2560x1080
**Java version:** 8u301

**Steps to reproduce issue:**
1. Open LSML
2. Open a mech that has a + max heat quirk (eg, CRB-27B), equip with engine with at least a 250 rated engine
3. Open a mech with does not have a + max heat quirk, equip with same sized engine as above.

**Actual result:**
Both mechs have same capacity noted on right hand side

**Expected result:**
Mech with max heat quirk should have more capacity (eg, CRB-27B should have a heat capacity of 48 * 1.15 = 55.2 for 10 double heat sinks)

![image](https://user-images.githubusercontent.com/82986066/155662740-eb99d2e8-dd02-4df2-ae2c-1a74744d74aa.png)

**Comment by LiSongMWO** [comment]
I did some testing using: `A<592000|Mgp00q00r00|^?s00|^?|^?t00u00v00w000000`.

Unmodified heat capacity: 30 + 20 (a fix in the upcoming LSML version, #767 ).
Generated head: 34+14
Observed heat % in game: 88%
Expected heat if the quirk applies to whole capacity: `(34+14)/(50*1.15) = 83.5%`
Expected heat if the quirk applies to base 30 capacity: `(34+14)/(30*1.15+20) = 88.0%`

Second test using `A<580000|Mgp00|h^|h^|h^|h^|h^|h^|h^q00r00|^?s00|^?|^?|h^|h^|h^t00u00v00w000000`.

Expected heat if quirk applies to base 30 capacity: `(34+14)/(30*1.15+31) = 73.3%`
Observed heat: 72%

Not sure if the observed difference is a rendering thing in the UI or server lag, needs more investigation.

**Comment by LiSongMWO** [comment]
I used the rounded heat, `34+14` with more precision the heat is `34.2 + 14.364`.

Re-running numbers for first mech:
Expected heat if the quirk applies to whole capacity: `(34.2 + 14.364)/(50*1.15) = 84.45%`
Expected heat if the quirk applies to base 30 capacity: `(34.2 + 14.364)/(30*1.15+20) = 89.1%`
Note discrepancy: 88% vs 89%.

Re-running numbers for second mech:
Expected heat if quirk applies to base 30 capacity: `(34.2 + 14.364)/(30*1.15+31) = 74.14%`
Expected heat if quirk applies to base full capacity: `(34.2 + 14.364)/(61*1.15) = 69.22%`
Observed heat: `72%`

The discrepancy is too large for the calculations to be correct.  Might be something with how ghost heat interacts with the -5% energy quirk.

IS ER PPC has 12 heat. 3 of them produces 36 base heat and 15.12 ghost heat according to LSML without any modifiers. 

Hypothesis 1: -5% energy heat applies to heat after ghost heat.
`0.95*(36+15.12) / (30*1.15+31) = 74.14%` - Doesn't seem corret.

Hypothesis 2: -5% energy heat is applied to weapon base heat before calculating ghost heat (current behaviour of LSML) and also to the result of the ghost heat (new).
`(34.2 + 0.95*14.364) / (30*1.15+31) = 73.05%` - Better but still not correct. However the discrepancy would be in line with the discrepancy above and could be explained by rounding/display issue in the client.

I will investigate further in #779. For now it seems more likely that the max heat quirk only applies to the base 30% heat.

**Comment by LiSongMWO** [comment]
Posting this here for posterity: The heat dial is not to be relied upon for test results relating to heat capacity. Only the binary results with respect to overheat or not are reliable due to inter frame timing and display refreshes and animation timing. 

Verifying that the `HEAT` modifier is applied correctly in absence of any modifiers on heat capacity:

Using AS7-KR `Ag:020a1|ab|I@p=1|i^|i^|i^|i^q=1|i^|i^|i^|i^r41|I@s41|I@|a?|i^t@1uB1vB0w;07070` the current LSML develop branch head says that the mech has 99% alpha heat and will not overheat. This has been confirmed in game. By removing one heatsink, the expected alpha heat exceeds the capacity by 0.2. The ingame behaviour is also an overheat.

With one DHS removed:
Unmodified heat capacity: 54
Alpha heat: `27+27.216 = 54.216`

It is reasonable to believe that LSML computes the capacity and alpha heat for this build correctly, even in the presence of the `HEAT: -10%` modifier.

Moving on to testing `MAX HEAT: 15%` with the CRB-27B and discerning how the modifier is applied:

Let's assume the 15% applies only on base 30 capacity, total capacity is then: `30*1.15 + 20 = 54.5`
With 2x ERPPC and 1 HEAVY PPC, alpha heat generated is: `35.15+15.561 = 50.711`, or 93%.
`A<592000|Mgp00q00r00|^?s00|^?|H@t00u00v00w000000`
Observed: 92%, no overheat.

With 3x SNUBNOSE and 1x PPC, we expect alpha heat of: `(28.5+28.728)/54.5 = 105%`
`A<592000|Mg|I@p00q00r00|I@|I@s00|a?t00u00v00w000000`
Observed: Overheat, above 100% for what seems like a resonable time to drop about 5%.

Adding 5 DHS increases heat base to `57 (54.5 + 5*0.5=2.5)`, no overheat expected.
`A<582000|I@|Edp00|i^|i^|i^q00r00|I@|I@s00|a?|i^|i^t00u00v00w000000`
Observed: No overheat, 99% on the dial.
Removing 1 DHS, expecting overheat.
Observed: Overheat.

Testing with SHS:
`A<580000|I@|Edp00|h^|h^q00r00|a?s00|a?|a?|h^|h^|h^t00u00v00w000000`
Capacity: `30*1.15 + 10*2.25+ 5*0.85 = 61.25`
Heat: `32.3+28.728 = 61.028`
Expected: No overheat.
Observed: No overheat.
Removing one SHS drops capacity to 60.40, expecting overheat.
Observed: Overheat.

It seems reasonable to conclude that the hypothesis is correct. And that dial readings should not be relied upon for verification of test results.

These results have been obtained on testing grounds and as such need to be verified on a live game server. I do not currently own any CRB.

@RosariusAU could you please verify my results above in a live game by following the 4 steps below?
1) Import `A<582000|I@|Edp00|i^|i^|i^q00r00|I@|I@s00|a?|i^|i^t00u00v00w000000` (CRB-27B) and fire an alpha at 0% heat while standing still. Did it overheat?
2) Remove one DHS, and repeat. Did it overheat?
3) Import `A<580000|I@|Edp00|h^|h^q00r00|a?s00|a?|a?|h^|h^|h^t00u00v00w000000` (CRB-27B) and fire an alpha at 0% heat while standing still. Did it overheat?
4) Remove one SHS, and repeat. Did it overheat?

**Comment by RosariusAU** [comment]
> These results have been obtained on testing grounds and as such need to be verified on a live game server. I do not currently own any CRB.
> 
> @RosariusAU could you please verify my results above in a live game by following the 4 steps below?
> 
> 1. Import `A<582000|I@|Edp00|i^|i^|i^q00r00|I@|I@s00|a?|i^|i^t00u00v00w000000` (CRB-27B) and fire an alpha at 0% heat while standing still. Did it overheat?
> 2. Remove one DHS, and repeat. Did it overheat?
> 3. Import `A<580000|I@|Edp00|h^|h^q00r00|a?s00|a?|a?|h^|h^|h^t00u00v00w000000` (CRB-27B) and fire an alpha at 0% heat while standing still. Did it overheat?
> 4. Remove one SHS, and repeat. Did it overheat?

I cannot right at this moment but I'll test with video footage and get back to you in the next 1-2 days :)

I appreciate the work you put into LSML and I do hope that the cookies are suitable compensation!

**Comment by RosariusAU** [comment]
Looking back on your instructions, I might have done a dumb and misinterpreted what you asked me to do... nevertheless here are my findings https://www.youtube.com/watch?v=wZDsVPfjVEw 

1. No overheat
2. Shut down
3. No overheat
4. Shut down

Please let me know if you needed me to redo the test with override engaged

**Comment by LiSongMWO** [comment]
Based on the timer in the top, the ping display and the announcer voice, I guess this was done in a private lobby?

I think that the test was done correctly, thank you that confirms my findings. :) I can apply the fix now. I find it fascinating that the 15% boost only applies to the 30 base heat capacity because it makes the quirk far less valuable than it would appear from the description. And its behaviour is kind of opaque to the player...
