### ISSUE TITLE
Weapons table doesn't update on omnipod change

### ISSUE THREAD

**Issue by astro-hemlow** [lisongmechlab/lsml#783]
**LSML version:** 2.0.15 pre-release

**Steps to reproduce issue:**
1. Open LSML
2. Open a KFX-PR 
3. Equip c-uac10 + 1 ton ammo.
4. Change left arm between KFX-PR (c-uac10 ammo +45) and KFX-P (c-uac10 ammo +60) and KFX-S (no ammo quirk).
5. Read Armaments table.

**Actual result:**
Table should show different values (rnds, dmg, etc) due to different amounts of ammo from the quirks.

**Expected result:**
Same values no matter what arm – the different ammo quirks seems to not affect the values.

**Comment by LiSongMWO** [comment]
Compare http://t.li-soft.org/?l=rwHcAhoCHBIlAxoCHBQMlIF4lPNh5vPNAeajzccm2sXp to http://t.li-soft.org/?l=rwHcAhoCHBIlAxoCHBQMlIHm082Hm880B5qPNx5paxem both are KFX-PR with 1 C-UAC10 with 1 ton of ammo but different arm omnipods so that the latter has quirks and the former doesn't.

The one without quirks shows: 69 rounds (nice), 23 volleys, 51 seconds and 230 damage.
The one with quirks shows: 114 rounds, 38 volleys, 80 seconds and 380 damage.
The sum of the quirks add 45 ammo: 69 + 45 = 114. It seems like the correct amount of ammo is applied.

However changing the omnipod doesn't seem to update the ammo table. Changing the loadout in other ways or closing and opening it again will restore the weapons table as a workaround for now.
