### ISSUE TITLE
Increase default window sizes to better fit contents.

### ISSUE THREAD

**Issue by sestrand** [lisongmechlab/lsml#793]
**LSML version:** 2.0.14
**Screen resolution:** 3440x1440
**Java version:** 8uX

Min screen requirement is too small and now limits what is possible in the weapons lab (and perhaps other pages).

There... no hijacked thread.  :-)

**Comment by LiSongMWO** [comment]
What action needs to be taken to close this issue? What's the definition of done?

**Comment by sestrand** [comment]
I think just changing the default width of the app will suffice.  make it big enough that when you open the weapons page, all columns are visible by default.  (including any that might be added from smurfy) . 

a bit wider would also get all of the quirks visible by default with create new 'Mech

**Comment by LiSongMWO** [comment]
Many parts of the UI don't really have a "default size" in that sense. They are automatically sized to exactly fit the contents, this, together with vector graphics for icons etc. means that LSML scales graciously between different display DPIs and scale factors. However the contents were carefully chosen so that at 96 DPI (default at the time) and 1024x768 resolution, things would fit on the screen. 

I think that what is the real problem is the "modal" windows that open inside of other windows (new mech and weapon lab). As I don't think that these are taken into account when sizing the parent windows. I think that these should probably be made into top level windows that can be moved indenpendently and then the autosizing would work for them as well.

I see the problem with the weapons table I'll se if I can change the sizing constraints on this.

There are some glitches that I want to fix though.

**Comment by sestrand** [comment]
I like the new look. very clean.
